apiVersion: apps/v1
kind: Deployment
metadata:
  name: n8n
  labels:
    service: n8n
spec:
  replicas: 1
  selector:
    matchLabels:
      service: n8n
  template:
    metadata:
      labels:
        service: n8n
    spec:
      serviceAccountName: default  # 确保已绑定 anyuid SCC
      containers:
        - name: n8n
          image: n8nio/n8n:latest
          env:
            - name: N8N_EDITOR_BASE_URL
              value: https://n8n-n8n.apps.obs-hub-of-hubs-aws-418-sno-v9w92.scale.red-chesterfield.com
            - name: WEBHOOK_URL
              value: https://n8n-n8n.apps.obs-hub-of-hubs-aws-418-sno-v9w92.scale.red-chesterfield.com
            - name: DB_TYPE
              value: postgresdb
            - name: DB_POSTGRESDB_HOST
              value: postgres-service.n8n.svc.cluster.local
            - name: DB_POSTGRESDB_PORT
              value: "5432"
            - name: DB_POSTGRESDB_DATABASE
              value: n8n
            - name: N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS
              value: "true"
            - name: N8N_RUNNERS_ENABLED
              value: "true"
            - name: N8N_LISTEN_PROXY_REQUESTS
              value: "true"
            - name: N8N_TRUST_PROXY
              value: "true"
            - name: NODE_ENV
              value: "production"
            - name: N8N_PROXY_HOPS
              value: "1"
            - name: N8N_PUSH_BACKEND
              value: "websocket"        
            - name: DB_POSTGRESDB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_NON_ROOT_USER
            - name: DB_POSTGRESDB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_NON_ROOT_PASSWORD
            - name: N8N_PROTOCOL
              value: http
            - name: N8N_PORT
              value: "5678"
            - name: N8N_USER_FOLDER
              value: "/home/node/.n8n"
            - name: HOME
              value: "/home/node"
          ports:
            - containerPort: 5678
          resources:
            requests:
              memory: "250Mi"
            limits:
              memory: "500Mi"
          volumeMounts:
            - mountPath: /home/node/.n8n
              name: n8n-claim0
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
      volumes:
        - name: n8n-claim0
          persistentVolumeClaim:
            claimName: n8n-claim0
        - name: n8n-secret
          secret:
            secretName: n8n-secret
        - name: postgres-secret
          secret:
            secretName: postgres-secret
