apiVersion: v1
kind: Secret
metadata:
  namespace: n8n
  name: postgres-secret
type: Opaque
stringData:
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: Letmein123
  POSTGRES_DB: n8n
  POSTGRES_NON_ROOT_USER: user1
  POSTGRES_NON_ROOT_PASSWORD: user1
